<?php

return [
    'recording_method' => [
        'type' => 'batch',
        'allow_multiple_batches' => true,
        'batch_settings' => [
            'enabled' => true,
            'auto_generate_batch' => true,
            'require_batch_number' => false,
            'depletion_method_default' => 'fifo',
            'depletion_methods' => [
                'fifo' => [
                    'enabled' => true,
                    'status' => 'ready',
                    'track_age' => true,
                    'auto_select' => true,
                    'min_age_days' => 0,
                    'max_age_days' => null,
                    'prefer_older_batches' => true,
                    'age_calculation_method' => 'start_date',
                    'batch_selection_criteria' => [
                        'primary' => 'age',
                        'secondary' => 'quantity',
                        'tertiary' => 'health_status'
                    ],
                    'quantity_distribution' => [
                        'method' => 'proportional',
                        'allow_partial_batch_depletion' => true,
                        'min_batch_remaining' => 0,
                        'preserve_batch_integrity' => false,
                        'max_batches_per_operation' => 5,
                        'force_single_batch' => true,
                        'prefer_complete_batch_depletion' => false
                    ],
                    'validation_rules' => [
                        'check_batch_availability' => true,
                        'validate_quantity_limits' => true,
                        'check_batch_status' => true,
                        'require_active_batches_only' => true
                    ],
                    'performance_optimization' => [
                        'cache_batch_queries' => true,
                        'batch_query_limit' => 100,
                        'use_indexed_queries' => true,
                        'parallel_processing' => false
                    ],
                    'audit_trail' => [
                        'track_depletion_history' => true,
                        'store_batch_snapshots' => true,
                        'log_decision_factors' => true,
                        'include_config_snapshot' => true
                    ]
                ],
                'lifo' => [
                    'enabled' => false,
                    'status' => 'not_applicable',
                    'track_age' => false,
                    'auto_select' => false,
                ],
                'manual' => [
                    'enabled' => false,
                    'status' => 'not_applicable',
                    'history_enabled' => false,
                    'track_age' => true,
                    'auto_select' => false,
                    'show_batch_details' => true,
                    'require_selection' => true,
                ],
            ],
            'mutation_method_default' => 'fifo',
            'mutation_methods' => [
                'fifo' => [
                    'enabled' => true,
                    'status' => 'ready',
                    'track_age' => true,
                    'auto_select' => true,
                    'min_age_days' => 0,
                    'max_age_days' => null,
                    'prefer_older_batches' => true,
                    'age_calculation_method' => 'start_date',
                    'input_restrictions' => [
                        'allow_same_day_repeated_input' => true,
                        'allow_same_livestock_repeated_input' => true,
                        'allow_same_livestock_same_day' => false,
                        'batch_selection_control' => 'automatic',
                        'allow_batch_override_reason' => false,
                        'max_mutation_per_day_per_batch' => 10,
                        'max_mutation_per_day_per_livestock' => 10,
                        'require_unique_purpose' => false,
                        'min_interval_minutes' => 0,
                        'max_entries_per_session' => 20,
                        'prevent_duplicate_stocks' => true,
                        'allow_partial_stock_usage' => true,
                        'require_stock_availability_check' => true,
                        'max_stock_age_days' => 365,
                        'warn_on_old_stock' => true,
                        'old_stock_threshold_days' => 90,
                    ],
                    'batch_selection_criteria' => [
                        'primary' => 'age',
                        'secondary' => 'quantity',
                        'tertiary' => 'health_status'
                    ],
                    'quantity_distribution' => [
                        'method' => 'sequential',
                        'allow_partial_batch_depletion' => true,
                        'min_batch_remaining' => 0,
                        'preserve_batch_integrity' => false,
                        'max_batches_per_operation' => 1,
                        'force_single_batch' => true,
                        'prefer_complete_batch_depletion' => false
                    ],
                    'validation_rules' => [
                        'check_batch_availability' => true,
                        'validate_quantity_limits' => true,
                        'check_batch_status' => true,
                        'require_active_batches_only' => true
                    ],
                    'performance_optimization' => [
                        'cache_batch_queries' => true,
                        'batch_query_limit' => 100,
                        'use_indexed_queries' => true,
                        'parallel_processing' => false
                    ],
                    'audit_trail' => [
                        'track_depletion_history' => true,
                        'store_batch_snapshots' => true,
                        'log_decision_factors' => true,
                        'include_config_snapshot' => true
                    ]
                ],
                'lifo' => [
                    'enabled' => false,
                    'status' => 'not_applicable',
                    'track_age' => false,
                    'auto_select' => false,
                ],
                'manual' => [
                    'enabled' => false,
                    'status' => 'not_applicable',
                    'history_enabled' => false,
                    'track_age' => true,
                    'auto_select' => false,
                    'show_batch_details' => true,
                    'require_selection' => true,
                    'input_restrictions' => [
                        'allow_same_day_repeated_input' => true,
                        'allow_same_batch_repeated_input' => true,
                        'max_mutation_per_day_per_batch' => 50,
                        'max_mutation_per_day_per_livestock' => 100,
                        'require_unique_purpose' => false,
                        'min_interval_minutes' => 0,
                        'max_entries_per_session' => 20,
                        'prevent_duplicate_stocks' => true,
                        'allow_partial_stock_usage' => true,
                        'require_stock_availability_check' => true,
                        'max_stock_age_days' => 365,
                        'warn_on_old_stock' => true,
                        'old_stock_threshold_days' => 90,
                    ],
                ],
            ],
            'feed_usage_method_default' => 'fifo',
            'feed_usage_methods' => [
                'fifo' => [
                    'enabled' => true,
                    'status' => 'ready',
                    'track_age' => true,
                    'auto_select' => true,
                    'min_age_days' => 0,
                    'max_age_days' => null,
                    'prefer_older_batches' => true,
                    'age_calculation_method' => 'start_date',
                    'batch_selection_criteria' => [
                        'primary' => 'age',
                        'secondary' => 'quantity',
                        'tertiary' => 'health_status'
                    ],
                    'quantity_distribution' => [
                        'method' => 'sequential',
                        'allow_partial_batch_depletion' => true,
                        'min_batch_remaining' => 0,
                        'preserve_batch_integrity' => false,
                        'max_batches_per_operation' => 1,
                        'force_single_batch' => true,
                        'prefer_complete_batch_depletion' => false
                    ],
                    'validation_rules' => [
                        'check_batch_availability' => true,
                        'validate_quantity_limits' => true,
                        'check_batch_status' => true,
                        'require_active_batches_only' => true
                    ],
                    'performance_optimization' => [
                        'cache_batch_queries' => true,
                        'batch_query_limit' => 100,
                        'use_indexed_queries' => true,
                        'parallel_processing' => false
                    ],
                    'audit_trail' => [
                        'track_depletion_history' => true,
                        'store_batch_snapshots' => true,
                        'log_decision_factors' => true,
                        'include_config_snapshot' => true
                    ]
                ],
                'lifo' => [
                    'enabled' => false,
                    'status' => 'not_applicable',
                    'track_age' => false,
                    'auto_select' => false,
                ],
                'manual' => [
                    'enabled' => true,
                    'status' => 'ready',
                    'track_age' => true,
                    'auto_select' => false,
                    'show_batch_details' => true,
                    'require_selection' => true,
                    'validation_rules' => [
                        'require_usage_date' => true,
                        'require_usage_purpose' => true,
                        'require_quantity' => true,
                        'require_notes' => false,
                        'min_quantity' => 0.1,
                        'max_quantity' => 10000,
                        'allow_zero_quantity' => false,
                    ],
                    'input_restrictions' => [
                        'allow_same_day_repeated_input' => true,
                        'allow_same_batch_repeated_input' => true,
                        'max_usage_per_day_per_batch' => 50,
                        'max_usage_per_day_per_livestock' => 100,
                        'require_unique_purpose' => false,
                        'min_interval_minutes' => 0,
                        'max_entries_per_session' => 20,
                        'prevent_duplicate_stocks' => true,
                        'allow_partial_stock_usage' => true,
                        'require_stock_availability_check' => true,
                        'max_stock_age_days' => 365,
                        'warn_on_old_stock' => true,
                        'old_stock_threshold_days' => 90,
                    ],
                    'workflow_settings' => [
                        'enable_preview_step' => true,
                        'require_confirmation' => true,
                        'auto_save_draft' => false,
                        'enable_batch_info_display' => true,
                        'show_stock_details' => true,
                        'show_cost_information' => true,
                        'enable_usage_history' => true,
                    ],
                    'batch_selection' => [
                        'show_batch_details' => true,
                        'show_current_quantity' => true,
                        'show_age_information' => true,
                        'show_coop_information' => true,
                        'show_strain_information' => true,
                        'enable_batch_filtering' => true,
                        'default_sort' => 'age_asc',
                        'hide_inactive_batches' => true,
                        'min_batch_quantity' => 1,
                    ],
                    'stock_selection' => [
                        'show_stock_details' => true,
                        'show_availability' => true,
                        'show_cost_per_unit' => true,
                        'show_batch_info' => true,
                        'show_age_days' => true,
                        'enable_stock_filtering' => true,
                        'default_sort' => 'age_asc',
                        'hide_unavailable_stocks' => true,
                        'warn_on_low_stock' => true,
                        'low_stock_threshold' => 10,
                    ],
                    'edit_mode_settings' => [
                        'edit_strategy' => 'update',
                        'delete_strategy' => 'soft',
                        'create_backup_before_edit' => true,
                        'track_edit_operations' => true,
                        'soft_delete_settings' => [
                            'increment_usage_count' => true,
                            'default_delete_reason' => 'edited',
                            'preserve_original_data' => true,
                        ],
                        'hard_delete_settings' => [
                            'validate_references' => true,
                            'restore_stock_quantities' => true,
                            'update_livestock_totals' => true,
                        ],
                        'update_settings' => [
                            'track_field_changes' => true,
                            'validate_business_rules' => true,
                            'update_timestamps' => true,
                        ],
                        'notifications' => [
                            'notify_on_edit' => true,
                            'notify_on_delete_recreate' => true,
                            'include_change_summary' => true,
                        ],
                    ],
                ],
            ],
            'batch_tracking' => [
                'enabled' => true,
                'track_individual_batches' => true,
                'track_batch_performance' => true,
                'batch_aging' => true,
            ],
            'validation_rules' => [
                'require_batch_selection' => true,
                'allow_partial_batch_usage' => true,
                'max_batches_per_recording' => 5,
                'min_batch_quantity' => 1,
            ],
        ],
    ],
    'lifecycle_management' => [
        'enabled' => true,
        'stages' => [
            'arrival' => [
                'enabled' => true,
                'require_health_check' => true,
                'require_initial_weight' => true,
                'require_initial_count' => true,
            ],
            'growth' => [
                'enabled' => true,
                'weight_monitoring' => true,
                'health_monitoring' => true,
                'feed_monitoring' => true,
            ],
            'harvest' => [
                'enabled' => true,
                'require_weight_final' => true,
                'require_health_final' => true,
                'require_harvest_date' => true,
            ],
        ],
        'age_tracking' => [
            'enabled' => true,
            'calculate_from' => 'start_date',
            'age_units' => 'days',
            'track_age_by_batch' => true,
        ],
    ],
    'health_management' => [
        'enabled' => true,
        'vaccination_tracking' => [
            'enabled' => true,
            'require_vaccination_schedule' => true,
            'track_vaccination_history' => true,
        ],
        'disease_tracking' => [
            'enabled' => true,
            'require_disease_reporting' => true,
            'track_treatment_history' => true,
        ],
        'medication_tracking' => [
            'enabled' => true,
            'require_prescription' => true,
            'track_medication_history' => true,
        ],
    ],
    'depletion_tracking' => [
        'enabled' => true,
        'types' => [
            'mortality' => [
                'enabled' => true,
                'track_by_batch' => true,
                'batch_attribution' => 'auto',
            ],
            'culling' => [
                'enabled' => true,
                'require_reason' => true,
                'track_by_batch' => true,
                'batch_attribution' => 'manual',
            ],
            'sales' => [
                'enabled' => true,
                'require_price' => true,
                'track_by_batch' => true,
                'batch_attribution' => 'manual',
            ],
        ],
        'input_restrictions' => [
            'allow_same_day_repeated_input' => true,
            'allow_same_batch_repeated_input' => true,
            'max_depletion_per_day_per_batch' => 10,
            'require_unique_reason' => false,
            'allow_zero_quantity' => false,
            'min_interval_minutes' => 0,
        ],
    ],
    'weight_tracking' => [
        'enabled' => true,
        'unit' => 'gram',
        'precision' => 2,
        'weight_gain_calculation' => true,
        'track_by_batch' => true,
        'batch_weight_method' => 'average',
    ],
    'feed_tracking' => [
        'enabled' => true,
        'require_feed_type' => true,
        'require_quantity' => true,
        'fcr_calculation' => true,
        'track_by_batch' => true,
        'batch_feed_allocation' => 'proportional',
    ],
    'feed_usage' => [
        'enabled' => true,
        'methods' => [
            'auto' => [
                'enabled' => true,
                'method' => 'fifo',
                'require_batch_selection' => false,
            ],
            'manual' => [
                'enabled' => true,
                'require_batch_selection' => true,
                'allow_multiple_batches' => true,
                'validation_rules' => [
                    'require_usage_date' => true,
                    'require_usage_purpose' => true,
                    'require_quantity' => true,
                    'require_notes' => false,
                    'min_quantity' => 0.1,
                    'max_quantity' => 10000,
                    'allow_zero_quantity' => false,
                ],
                'input_restrictions' => [
                    'allow_same_day_repeated_input' => true,
                    'allow_same_batch_repeated_input' => true,
                    'max_usage_per_day_per_batch' => 50,
                    'max_usage_per_day_per_livestock' => 100,
                    'require_unique_purpose' => false,
                    'min_interval_minutes' => 0,
                    'max_entries_per_session' => 20,
                    'prevent_duplicate_stocks' => true,
                    'allow_partial_stock_usage' => true,
                    'require_stock_availability_check' => true,
                    'max_stock_age_days' => 365,
                    'warn_on_old_stock' => true,
                    'old_stock_threshold_days' => 90,
                ],
            ],
        ],
        'tracking' => [
            'enabled' => true,
            'track_by_batch' => true,
            'track_usage_history' => true,
            'track_cost_per_usage' => true,
            'track_efficiency_metrics' => true,
            'enable_analytics' => true,
        ],
        'notifications' => [
            'enabled' => true,
            'notify_on_completion' => true,
            'notify_on_low_stock' => true,
            'notify_on_old_stock_usage' => true,
            'notify_on_high_usage' => false,
        ],
    ],
    'performance_metrics' => [
        'enabled' => true,
        'metrics' => [
            'fcr' => true,
            'ip' => true,
            'adg' => true,
            'mortality_rate' => true,
            'liveability' => true,
        ],
        'calculation_frequency' => 'daily',
        'track_by_batch' => true,
    ],
    'cost_tracking' => [
        'enabled' => true,
        'purchase_cost' => [
            'enabled' => true,
            'include_transport' => true,
            'track_unit_cost' => true,
        ],
        'operational_cost' => [
            'enabled' => true,
            'feed_cost' => true,
            'medical_cost' => true,
        ],
        'profitability_analysis' => [
            'enabled' => true,
            'include_all_costs' => true,
            'calculate_roi' => true,
        ],
    ],
    'validation_rules' => [
        'enabled' => false,
        'require_farm' => true,
        'require_coop' => true,
        'require_start_date' => true,
        'require_initial_quantity' => true,
        'min_quantity' => 1,
        'max_quantity' => 100000,
    ],
    'reporting' => [
        'enabled' => true,
        'reports' => [
            'inventory_report' => ['enabled' => true, 'frequency' => 'daily'],
            'performance_report' => ['enabled' => true, 'frequency' => 'weekly'],
            'cost_report' => ['enabled' => true, 'frequency' => 'monthly'],
            'health_report' => ['enabled' => true, 'frequency' => 'weekly'],
        ],
        'dashboards' => [
            'enabled' => true,
            'real_time_monitoring' => true,
            'alert_thresholds' => [
                'mortality_rate' => 5,
                'weight_gain' => 0.05,
                'health_incidents' => 10,
            ],
        ],
    ],
    'documentation' => [
        'enabled' => true,
        'require_notes' => false,
        'require_photos' => false,
        'batch_documentation' => [
            'enabled' => true,
            'track_batch_history' => true,
        ],
        'health_documentation' => [
            'enabled' => true,
            'track_health_incidents' => true,
            'track_treatments' => true,
        ],
    ],
];
