<?php

namespace App\Providers;

use App\Core\KTBootstrap;
use Illuminate\Database\Schema\Builder;
use Illuminate\Support\ServiceProvider;
// use App\Livewire\MasterData\SupplierModal;
use Livewire\Livewire; // Import the facade
use App\Livewire\QaChecklistForm;
use App\Models\Role;
use App\Models\Permission;
use App\Observers\RoleObserver;
use App\Observers\PermissionObserver;
use App\Observers\LivestockDepletionObserver;
use App\Models\LivestockDepletion;
use Laravel\Sanctum\Sanctum;
use App\Models\PersonalAccessToken;
use App\Models\Company;
use App\Observers\CompanyObserver;
use App\Services\Recording\Contracts\RecordingDataServiceInterface;
use App\Services\Recording\RecordingDataService;
use App\Services\Recording\Contracts\RecordingPersistenceServiceInterface;
use App\Services\Recording\RecordingPersistenceService;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        // Bind the modular recording services to their contracts.
        // This allows us to easily swap implementations in the future.
        $this->app->bind(RecordingDataServiceInterface::class, RecordingDataService::class);
        $this->app->bind(RecordingPersistenceServiceInterface::class, RecordingPersistenceService::class);
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        // Update defaultStringLength
        Builder::defaultStringLength(191);

        KTBootstrap::init();

        $this->app->singleton('app.menu', function ($app) {
            $menuService = new \App\Services\MenuService();
            return $menuService->processMenu(config('xolution.menu'));
        });

        // Livewire::component('master-data.supplier-modal', SupplierModal::class);
        // Livewire::component('master-data.supplier', App\Livewire\MasterData\Supplier::class);

        // Register Livewire components
        Livewire::component('qa-checklist-form', QaChecklistForm::class);

        // Register observers
        Role::observe(RoleObserver::class);
        Permission::observe(PermissionObserver::class);
        LivestockDepletion::observe(LivestockDepletionObserver::class);

        // Auto-sync master data when company created
        Company::observe(CompanyObserver::class);

        // Force Sanctum to use our custom PersonalAccessToken model
        Sanctum::usePersonalAccessTokenModel(PersonalAccessToken::class);

        // =========================================
        // Share Version Information Globally
        // =========================================
        $detectedVersion = cache()->rememberForever('app_version', function () {
            $default = config('xolution.APPS.Version');

            // --- 1) Prefer .version file (auto-generated by CI) ---
            $versionFile = base_path('.version');
            if (file_exists($versionFile)) {
                $ver = trim(file_get_contents($versionFile));
                if (!empty($ver)) {
                    return $ver;
                }
            }

            // --- 2) Fallback: Parse first version heading in CHANGELOG.md ---
            $changelog = base_path('CHANGELOG.md');
            if (!file_exists($changelog)) {
                return $default;
            }

            $handle = fopen($changelog, 'r');
            if (! $handle) {
                return $default;
            }

            while (($line = fgets($handle)) !== false) {
                if (preg_match('/^##\s*\[?v?([0-9]+(?:\.[0-9]+)+)\]?/i', $line, $matches)) {
                    fclose($handle);
                    return strtoupper('V' . ltrim($matches[1], 'vV'));
                }
            }
            fclose($handle);

            return $default; // ultimate fallback
        });

        // Overwrite config value at runtime so existing calls continue to work
        config(['xolution.APPS.Version' => $detectedVersion]);

        // Share to all blade views
        view()->share('app_version', $detectedVersion);

        // Only load Pulse and Telescope migrations in local/dev
        if (app()->environment(['local', 'development', 'dev', 'testing'])) {
            $this->loadMigrationsFrom(database_path('migrations/pulse'));
            $this->loadMigrationsFrom(database_path('migrations/telescope'));
        }
    }
}
